using AniRuntime.Core.Models;
using AniRuntime.Memory.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AniRuntime.Memory;

/// <summary>
/// Phase 1 of data-layer refactor (2026-05-17) — EF Core DbContext for
/// the main ani-memory.db. Replaces the raw <c>Microsoft.Data.Sqlite</c>
/// composition in <c>SqliteMemoryService</c>, <c>SqliteConversationService</c>,
/// and <c>SqliteClosedConversationStore</c> with a unified context that
/// supports Unit of Work composition via <c>SaveChangesAsync</c>.
///
/// See <c>docs/spec/ANI-Data-Layer-UoW-Repository-Refactor-Plan.md</c> for
/// the full plan and <c>docs/spec/ANI-Data-Layer-Phase1-Inventory.md</c>
/// for the table+behavior inventory this entity set covers.
///
/// **Schema parity goal:** the schema generated by this context's
/// <see cref="OnModelCreating"/> must match the cumulative production
/// schema (initial CREATE TABLEs + all post-init ALTER TABLE migrations
/// in <c>SqliteMemoryService.InitialiseSchema</c>). Validated via the
/// Phase 1.7 schema-diff acceptance test.
/// </summary>
public class AniDbContext : DbContext
{
    public AniDbContext(DbContextOptions<AniDbContext> options) : base(options) { }

    // ── Main memory store ──────────────────────────────────────────────
    public DbSet<MemoryEntity>            Memories            { get; set; } = null!;
    public DbSet<MemoryLinkEntity>        MemoryLinks         { get; set; } = null!;
    public DbSet<MemoryContradictionEntity> MemoryContradictions { get; set; } = null!;
    public DbSet<MemoryAuditEntity>       MemoryAudit         { get; set; } = null!;

    // ── State blobs (singletons) ───────────────────────────────────────
    public DbSet<CharacterStateEntity>      CharacterState      { get; set; } = null!;
    public DbSet<DesireStateEntity>         DesireState         { get; set; } = null!;
    public DbSet<EmotionalStateBlobEntity>  EmotionalState      { get; set; } = null!;
    public DbSet<RelationshipHealthEntity>  RelationshipHealth  { get; set; } = null!;

    // ── Time-series + analytics ────────────────────────────────────────
    public DbSet<EmotionalStateHistoryEntity>  EmotionalStateHistory { get; set; } = null!;
    public DbSet<EmotionalContributionEntity>  EmotionalContributions { get; set; } = null!;
    public DbSet<ConfabulationFlagEntity>      ConfabulationFlags     { get; set; } = null!;

    // ── Conversation ───────────────────────────────────────────────────
    public DbSet<ConversationThreadEntity>     ConversationThreads     { get; set; } = null!;
    public DbSet<ConversationMessageEntity>    ConversationMessages    { get; set; } = null!;
    public DbSet<ClosedConversationRecordEntity> ClosedConversationRecords { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Value converters used across multiple entities.
        var guidToTextConverter = new ValueConverter<Guid, string>(
            g => g.ToString(),
            s => Guid.Parse(s));

        var floatArrayToBlobConverter = new ValueConverter<float[]?, byte[]?>(
            arr => arr == null ? null : FloatArrayToBytes(arr),
            blob => blob == null ? null : BytesToFloatArray(blob));

        // DateTimeOffset stored as ISO 8601 string (matches existing raw-SQL behavior).
        var dateTimeOffsetToStringConverter = new ValueConverter<DateTimeOffset, string>(
            dto => dto.ToString("o"),
            s => DateTimeOffset.Parse(s));

        var nullableDateTimeOffsetToStringConverter = new ValueConverter<DateTimeOffset?, string?>(
            dto => dto.HasValue ? dto.Value.ToString("o") : null,
            s => string.IsNullOrEmpty(s) ? null : DateTimeOffset.Parse(s));

        // ── MemoryEntity ────────────────────────────────────────────────
        modelBuilder.Entity<MemoryEntity>(entity =>
        {
            entity.Property(e => e.Id).HasConversion(guidToTextConverter);
            entity.Property(e => e.Type).HasConversion<int>(); // INTEGER not text
            entity.Property(e => e.Embedding).HasConversion(floatArrayToBlobConverter);
            entity.Property(e => e.OccurredAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.Property(e => e.CreatedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.Property(e => e.ResolvedAt).HasConversion(nullableDateTimeOffsetToStringConverter);
            entity.Property(e => e.AnchoredAt).HasConversion(nullableDateTimeOffsetToStringConverter);
            entity.Property(e => e.ConfirmedAt).HasConversion(nullableDateTimeOffsetToStringConverter);
            entity.Property(e => e.Tier).HasConversion<string>();           // DecayTier as TEXT
            entity.Property(e => e.Provenance).HasConversion<string>();     // EpistemicTier as TEXT
            entity.HasIndex(e => e.Type).HasDatabaseName("ix_memories_type");
            entity.HasIndex(e => e.OccurredAt).HasDatabaseName("ix_memories_occurred").IsDescending();
            // Issue #62 (2026-05-23) — walk-back substrate-correction.
            entity.HasIndex(e => e.Validity).HasDatabaseName("ix_memories_validity");
            // Issue #93 (2026-07-06) — retrieval-bias filter uses IS NOT NULL.
            entity.HasIndex(e => e.ConfirmedAt).HasDatabaseName("ix_memories_confirmed_at");
        });

        // ── MemoryLinkEntity (composite PK + 2 FKs to memories) ────────
        modelBuilder.Entity<MemoryLinkEntity>(entity =>
        {
            entity.HasKey(e => new { e.SourceId, e.TargetId, e.Relationship });
            entity.Property(e => e.SourceId).HasConversion(guidToTextConverter);
            entity.Property(e => e.TargetId).HasConversion(guidToTextConverter);
            entity.Property(e => e.CreatedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => e.SourceId).HasDatabaseName("ix_memory_links_source");
            entity.HasIndex(e => e.TargetId).HasDatabaseName("ix_memory_links_target");

            // FKs to MemoryEntity. EF Core will generate the FK constraints.
            entity.HasOne<MemoryEntity>()
                .WithMany()
                .HasForeignKey(e => e.SourceId)
                .OnDelete(DeleteBehavior.NoAction);
            entity.HasOne<MemoryEntity>()
                .WithMany()
                .HasForeignKey(e => e.TargetId)
                .OnDelete(DeleteBehavior.NoAction);
        });

        // ── MemoryContradictionEntity (composite PK) ───────────────────
        modelBuilder.Entity<MemoryContradictionEntity>(entity =>
        {
            entity.HasKey(e => new { e.NewMemoryId, e.ExistingMemoryId });
            entity.Property(e => e.NewMemoryId).HasConversion(guidToTextConverter);
            entity.Property(e => e.ExistingMemoryId).HasConversion(guidToTextConverter);
            entity.Property(e => e.FlaggedAt).HasConversion(dateTimeOffsetToStringConverter);
        });

        // ── MemoryAuditEntity ──────────────────────────────────────────
        modelBuilder.Entity<MemoryAuditEntity>(entity =>
        {
            entity.Property(e => e.MemoryId).HasConversion(guidToTextConverter);
            entity.Property(e => e.OccurredAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => e.MemoryId).HasDatabaseName("ix_audit_memory");
            entity.HasIndex(e => e.OccurredAt).HasDatabaseName("ix_audit_time").IsDescending();
            entity.HasIndex(e => e.Action).HasDatabaseName("ix_audit_action");
        });

        // ── State blob singletons ──────────────────────────────────────
        // EF needs no extra config — INT PK + TEXT JSON column.

        // ── EmotionalStateHistoryEntity ────────────────────────────────
        modelBuilder.Entity<EmotionalStateHistoryEntity>(entity =>
        {
            entity.Property(e => e.RecordedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => e.RecordedAt).HasDatabaseName("ix_emotional_history_time").IsDescending();
        });

        // ── EmotionalContributionEntity ────────────────────────────────
        modelBuilder.Entity<EmotionalContributionEntity>(entity =>
        {
            entity.Property(e => e.Id).HasConversion(guidToTextConverter);
            entity.Property(e => e.Embedding).HasConversion(floatArrayToBlobConverter);
            entity.Property(e => e.CreatedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => e.CreatedAt).HasDatabaseName("ix_contributions_created").IsDescending();
        });

        // ── ConfabulationFlagEntity ────────────────────────────────────
        modelBuilder.Entity<ConfabulationFlagEntity>(entity =>
        {
            entity.Property(e => e.Id).HasConversion(guidToTextConverter);
            entity.Property(e => e.FlaggedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => e.FlaggedAt).HasDatabaseName("ix_confab_flags_time").IsDescending();
        });

        // ── ConversationThreadEntity ───────────────────────────────────
        modelBuilder.Entity<ConversationThreadEntity>(entity =>
        {
            entity.Property(e => e.Id).HasConversion(guidToTextConverter);
            entity.Property(e => e.StartedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.Property(e => e.LastMessageAt).HasConversion(dateTimeOffsetToStringConverter);
        });

        // ── ConversationMessageEntity ──────────────────────────────────
        modelBuilder.Entity<ConversationMessageEntity>(entity =>
        {
            entity.Property(e => e.ThreadId).HasConversion(guidToTextConverter);
            entity.Property(e => e.SentAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => new { e.ThreadId, e.SentAt }).HasDatabaseName("ix_conv_messages_thread");

            entity.HasOne<ConversationThreadEntity>()
                .WithMany()
                .HasForeignKey(e => e.ThreadId)
                .OnDelete(DeleteBehavior.NoAction);
        });

        // ── ClosedConversationRecordEntity ─────────────────────────────
        modelBuilder.Entity<ClosedConversationRecordEntity>(entity =>
        {
            entity.Property(e => e.Id).HasConversion(guidToTextConverter);
            entity.Property(e => e.ThreadId).HasConversion(guidToTextConverter);
            entity.Property(e => e.ClosedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.Property(e => e.Embedding).HasConversion(floatArrayToBlobConverter);
            entity.HasIndex(e => e.ClosedAt).HasDatabaseName("ix_closed_conv_closed_at").IsDescending();
            entity.HasIndex(e => e.ThreadId).HasDatabaseName("ix_closed_conv_thread_id");
        });
    }

    /// <summary>
    /// Issue #93 Phase 4 (2026-07-09) — idempotent init of the FTS5 virtual
    /// table + insert/update/delete triggers that keep <c>memories_fts</c>
    /// synced with <c>memories.content</c>. Called from application startup
    /// (Service + Eval) right after <c>EnsureCreatedAsync()</c>.
    ///
    /// <para>
    /// Motivation: pure-cosine retrieval buries entity-based confirmations
    /// (e.g. "Mark texted: 'hey babe! Back from teaching!'" ranked at cosine
    /// position 47/1557 for a semantically-emotional Interior record).
    /// SQLite FTS5's BM25 ranking finds it at position 1 because "teaching"
    /// is a rare token. The <c>EfSemanticSearchComposer</c> combines both
    /// signals via RRF fusion so entity-relevant records aren't lost.
    /// See docs/research/ANI-Retrieval-Consultation-2026-07-08.md.
    /// </para>
    ///
    /// <para>
    /// Uses the porter+unicode61 tokenizer for stemming (teach/teaching/taught
    /// map to the same token). Triggers propagate row changes from
    /// <c>memories</c> to <c>memories_fts</c> so the index stays fresh
    /// without application code needing to write both tables.
    /// </para>
    ///
    /// <para>Idempotent — <c>CREATE VIRTUAL TABLE IF NOT EXISTS</c> and
    /// <c>CREATE TRIGGER IF NOT EXISTS</c>. Safe to call on every startup.
    /// The backfill runs only when the FTS5 table is empty (fresh init or
    /// after external DROP).</para>
    /// </summary>
    /// <summary>
    /// Issue #93 Phase 1 (2026-07-09 rescue) — idempotent ALTER TABLE for
    /// the confirmed_at + confirmed_by columns. Production DBs that
    /// pre-date the 2026-07-06 SQL migration would otherwise crash EF at
    /// first-touch on memories with "no such column: m.confirmed_at".
    /// Fast (metadata-only ALTER on SQLite), safe inline at startup.
    ///
    /// <para>Also runs the Phase 1 canonical backfill (Facts+Episodic gets
    /// ConfirmedAt=CreatedAt, ConfirmedBy='canonical') on records that are
    /// still NULL. Single UPDATE statement, sub-second on a 25k-row DB.
    /// Idempotent: subsequent runs are no-ops once every eligible record
    /// is backfilled.</para>
    /// </summary>
    public async Task EnsureIssue93SchemaAsync(CancellationToken ct = default)
    {
        var conn = Database.GetDbConnection();
        if (conn.State != System.Data.ConnectionState.Open)
            await Database.OpenConnectionAsync(ct).ConfigureAwait(false);

        // Detect whether the columns already exist.
        await using var check = conn.CreateCommand();
        check.CommandText = "SELECT name FROM pragma_table_info('memories') WHERE name IN ('confirmed_at','confirmed_by')";
        var existing = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        await using (var reader = await check.ExecuteReaderAsync(ct).ConfigureAwait(false))
        {
            while (await reader.ReadAsync(ct).ConfigureAwait(false))
                existing.Add(reader.GetString(0));
        }

        await using var cmd = conn.CreateCommand();
        if (!existing.Contains("confirmed_at"))
        {
            cmd.CommandText = "ALTER TABLE memories ADD COLUMN confirmed_at TEXT NULL";
            await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
        if (!existing.Contains("confirmed_by"))
        {
            cmd.CommandText = "ALTER TABLE memories ADD COLUMN confirmed_by TEXT NULL";
            await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }

        cmd.CommandText = "CREATE INDEX IF NOT EXISTS ix_memories_confirmed_at ON memories (confirmed_at)";
        await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);

        // Canonical backfill: Facts + Episodic get birth-stamp confirmation.
        cmd.CommandText = @"
            UPDATE memories
            SET confirmed_at = created_at,
                confirmed_by = 'canonical'
            WHERE provenance IN ('Facts', 'Episodic')
              AND confirmed_at IS NULL";
        await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);

        // Feature 44 Phase I.3 (2026-08-05) — register column for the
        // qwen3:14b metadata-recognizer output. Idempotent add; NULL on
        // pre-shipping records pending backfill (backfill runs via the
        // eval CLI tool, not inline here — schema rescue is fast, LLM
        // classification of 2000+ records is not).
        await using var checkReg = conn.CreateCommand();
        checkReg.CommandText = "SELECT name FROM pragma_table_info('memories') WHERE name = 'register'";
        var hasRegister = false;
        await using (var reader = await checkReg.ExecuteReaderAsync(ct).ConfigureAwait(false))
        {
            if (await reader.ReadAsync(ct).ConfigureAwait(false))
                hasRegister = true;
        }
        if (!hasRegister)
        {
            cmd.CommandText = "ALTER TABLE memories ADD COLUMN register TEXT NULL";
            await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }

        // Issue #68 follow-on (2026-08-12) — retire the "substrate vector is
        // observed only, not yet consumed" TODO from EmotionalProcessor. Add
        // substrate_json to emotional_contributions so the EmoLLaMA-7B 15-axis
        // vector persists alongside the qwen3 register. Backfill of historical
        // records runs via the eval CLI (--backfill-substrate), not inline.
        await using var checkSub = conn.CreateCommand();
        checkSub.CommandText = "SELECT name FROM pragma_table_info('emotional_contributions') WHERE name = 'substrate_json'";
        var hasSubstrate = false;
        await using (var reader = await checkSub.ExecuteReaderAsync(ct).ConfigureAwait(false))
        {
            if (await reader.ReadAsync(ct).ConfigureAwait(false))
                hasSubstrate = true;
        }
        if (!hasSubstrate)
        {
            cmd.CommandText = "ALTER TABLE emotional_contributions ADD COLUMN substrate_json TEXT NULL";
            await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// Foundation Attribution (F-2) Phase 1 P2 (2026-08-21) — idempotent
    /// ALTER TABLE for the five attribution columns. Zero-risk additive
    /// migration: all columns nullable or with default; existing reads
    /// unaffected. Called at startup from Program.cs alongside
    /// <see cref="EnsureIssue93SchemaAsync"/>.
    ///
    /// <para>
    /// Columns added:
    /// <list type="bullet">
    ///   <item><c>attributed_to</c> INTEGER DEFAULT 0 (Unknown)</item>
    ///   <item><c>attributed_at</c> TEXT NULL</item>
    ///   <item><c>attributed_source_id</c> TEXT NULL (Guid FK to memories.id)</item>
    ///   <item><c>attributed_source_desc</c> TEXT NULL</item>
    ///   <item><c>attribution_trust</c> TEXT NOT NULL DEFAULT 'unverified'</item>
    /// </list>
    /// Plus indexes on <c>attributed_to</c> and <c>attribution_trust</c>.
    /// </para>
    ///
    /// <para>Heuristic backfill (per design plan D4) runs via the eval CLI
    /// tool (P3), not inline — schema rescue is fast, per-record attribution
    /// inference over 25k+ rows warrants a dedicated one-shot script.</para>
    ///
    /// <para>Idempotent: subsequent runs are no-ops once columns + indexes
    /// exist. Safe to call on every startup.</para>
    /// </summary>
    public async Task EnsureAttributionSchemaAsync(CancellationToken ct = default)
    {
        var conn = Database.GetDbConnection();
        if (conn.State != System.Data.ConnectionState.Open)
            await Database.OpenConnectionAsync(ct).ConfigureAwait(false);

        // Detect which columns already exist.
        await using var check = conn.CreateCommand();
        check.CommandText = @"
            SELECT name FROM pragma_table_info('memories')
            WHERE name IN (
                'attributed_to',
                'attributed_at',
                'attributed_source_id',
                'attributed_source_desc',
                'attribution_trust'
            )";
        var existing = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        await using (var reader = await check.ExecuteReaderAsync(ct).ConfigureAwait(false))
        {
            while (await reader.ReadAsync(ct).ConfigureAwait(false))
                existing.Add(reader.GetString(0));
        }

        await using var cmd = conn.CreateCommand();

        if (!existing.Contains("attributed_to"))
        {
            cmd.CommandText = "ALTER TABLE memories ADD COLUMN attributed_to INTEGER NOT NULL DEFAULT 0";
            await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
        if (!existing.Contains("attributed_at"))
        {
            cmd.CommandText = "ALTER TABLE memories ADD COLUMN attributed_at TEXT NULL";
            await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
        if (!existing.Contains("attributed_source_id"))
        {
            cmd.CommandText = "ALTER TABLE memories ADD COLUMN attributed_source_id TEXT NULL";
            await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
        if (!existing.Contains("attributed_source_desc"))
        {
            cmd.CommandText = "ALTER TABLE memories ADD COLUMN attributed_source_desc TEXT NULL";
            await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
        if (!existing.Contains("attribution_trust"))
        {
            cmd.CommandText = "ALTER TABLE memories ADD COLUMN attribution_trust TEXT NOT NULL DEFAULT 'unverified'";
            await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }

        cmd.CommandText = "CREATE INDEX IF NOT EXISTS ix_memories_attributed_to ON memories (attributed_to)";
        await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);

        cmd.CommandText = "CREATE INDEX IF NOT EXISTS ix_memories_attribution_trust ON memories (attribution_trust)";
        await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
    }

    public async Task EnsureFtsIndexAsync(CancellationToken ct = default)
    {
        await using var cmd = Database.GetDbConnection().CreateCommand();
        if (Database.GetDbConnection().State != System.Data.ConnectionState.Open)
            await Database.OpenConnectionAsync(ct).ConfigureAwait(false);

        // Virtual table + tokenizer.
        cmd.CommandText = @"
            CREATE VIRTUAL TABLE IF NOT EXISTS memories_fts USING fts5(
                content,
                memory_id UNINDEXED,
                tokenize='porter unicode61'
            );";
        await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);

        // Sync triggers — content-only. memories.content is the only field
        // that participates in FTS5; other changes to memories don't need
        // to touch the index.
        cmd.CommandText = @"
            CREATE TRIGGER IF NOT EXISTS memories_fts_ai AFTER INSERT ON memories
            BEGIN
                INSERT INTO memories_fts(memory_id, content) VALUES (new.id, new.content);
            END;

            CREATE TRIGGER IF NOT EXISTS memories_fts_ad AFTER DELETE ON memories
            BEGIN
                DELETE FROM memories_fts WHERE memory_id = old.id;
            END;

            CREATE TRIGGER IF NOT EXISTS memories_fts_au AFTER UPDATE OF content ON memories
            BEGIN
                DELETE FROM memories_fts WHERE memory_id = old.id;
                INSERT INTO memories_fts(memory_id, content) VALUES (new.id, new.content);
            END;";
        await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);

        // Backfill only if the FTS5 index is empty OR partially populated
        // relative to the memories table. Detect partial state (e.g. a
        // previous startup was killed mid-backfill by Windows SCM's 30s
        // deadline) by comparing row counts; if they differ by more than
        // a small tolerance, clear and rebuild.
        cmd.CommandText = "SELECT COUNT(*) FROM memories_fts";
        var ftsCount = Convert.ToInt64(await cmd.ExecuteScalarAsync(ct).ConfigureAwait(false));
        cmd.CommandText = "SELECT COUNT(*) FROM memories WHERE content IS NOT NULL AND content <> ''";
        var memoriesCount = Convert.ToInt64(await cmd.ExecuteScalarAsync(ct).ConfigureAwait(false));

        // Tolerance: allow a small skew (triggers may have queued rows just
        // arriving during startup). If FTS is empty or noticeably short of
        // memories, do a full rebuild.
        var needsRebuild = ftsCount == 0
                         || memoriesCount - ftsCount > 100
                         || ftsCount > memoriesCount + 100;
        if (needsRebuild)
        {
            if (ftsCount > 0)
            {
                cmd.CommandText = "DELETE FROM memories_fts";
                await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
            }
            cmd.CommandText = @"
                INSERT INTO memories_fts(memory_id, content)
                SELECT id, content FROM memories WHERE content IS NOT NULL AND content <> '';";
            await cmd.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// float[] → byte[] conversion using Buffer.BlockCopy.
    /// Each float = 4 bytes; total = floats.Length × 4.
    /// </summary>
    private static byte[] FloatArrayToBytes(float[] floats)
    {
        var bytes = new byte[floats.Length * sizeof(float)];
        Buffer.BlockCopy(floats, 0, bytes, 0, bytes.Length);
        return bytes;
    }

    private static float[] BytesToFloatArray(byte[] bytes)
    {
        var floats = new float[bytes.Length / sizeof(float)];
        Buffer.BlockCopy(bytes, 0, floats, 0, bytes.Length);
        return floats;
    }
}
