using AniRuntime.Core.Models;
using AniRuntime.Memory.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AniRuntime.Memory;

/// <summary>
/// Phase 1 of data-layer refactor (2026-05-17) — EF Core DbContext for
/// the main ani-memory.db. Replaces the raw <c>Microsoft.Data.Sqlite</c>
/// composition in <c>SqliteMemoryService</c>, <c>SqliteConversationService</c>,
/// and <c>SqliteClosedConversationStore</c> with a unified context that
/// supports Unit of Work composition via <c>SaveChangesAsync</c>.
///
/// See <c>docs/spec/ANI-Data-Layer-UoW-Repository-Refactor-Plan.md</c> for
/// the full plan and <c>docs/spec/ANI-Data-Layer-Phase1-Inventory.md</c>
/// for the table+behavior inventory this entity set covers.
///
/// **Schema parity goal:** the schema generated by this context's
/// <see cref="OnModelCreating"/> must match the cumulative production
/// schema (initial CREATE TABLEs + all post-init ALTER TABLE migrations
/// in <c>SqliteMemoryService.InitialiseSchema</c>). Validated via the
/// Phase 1.7 schema-diff acceptance test.
/// </summary>
public class AniDbContext : DbContext
{
    public AniDbContext(DbContextOptions<AniDbContext> options) : base(options) { }

    // ── Main memory store ──────────────────────────────────────────────
    public DbSet<MemoryEntity>            Memories            { get; set; } = null!;
    public DbSet<MemoryLinkEntity>        MemoryLinks         { get; set; } = null!;
    public DbSet<MemoryContradictionEntity> MemoryContradictions { get; set; } = null!;
    public DbSet<MemoryAuditEntity>       MemoryAudit         { get; set; } = null!;

    // ── State blobs (singletons) ───────────────────────────────────────
    public DbSet<CharacterStateEntity>      CharacterState      { get; set; } = null!;
    public DbSet<DesireStateEntity>         DesireState         { get; set; } = null!;
    public DbSet<EmotionalStateBlobEntity>  EmotionalState      { get; set; } = null!;
    public DbSet<RelationshipHealthEntity>  RelationshipHealth  { get; set; } = null!;

    // ── Time-series + analytics ────────────────────────────────────────
    public DbSet<EmotionalStateHistoryEntity>  EmotionalStateHistory { get; set; } = null!;
    public DbSet<EmotionalContributionEntity>  EmotionalContributions { get; set; } = null!;
    public DbSet<ConfabulationFlagEntity>      ConfabulationFlags     { get; set; } = null!;

    // ── Conversation ───────────────────────────────────────────────────
    public DbSet<ConversationThreadEntity>     ConversationThreads     { get; set; } = null!;
    public DbSet<ConversationMessageEntity>    ConversationMessages    { get; set; } = null!;
    public DbSet<ClosedConversationRecordEntity> ClosedConversationRecords { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Value converters used across multiple entities.
        var guidToTextConverter = new ValueConverter<Guid, string>(
            g => g.ToString(),
            s => Guid.Parse(s));

        var floatArrayToBlobConverter = new ValueConverter<float[]?, byte[]?>(
            arr => arr == null ? null : FloatArrayToBytes(arr),
            blob => blob == null ? null : BytesToFloatArray(blob));

        // DateTimeOffset stored as ISO 8601 string (matches existing raw-SQL behavior).
        var dateTimeOffsetToStringConverter = new ValueConverter<DateTimeOffset, string>(
            dto => dto.ToString("o"),
            s => DateTimeOffset.Parse(s));

        var nullableDateTimeOffsetToStringConverter = new ValueConverter<DateTimeOffset?, string?>(
            dto => dto.HasValue ? dto.Value.ToString("o") : null,
            s => string.IsNullOrEmpty(s) ? null : DateTimeOffset.Parse(s));

        // ── MemoryEntity ────────────────────────────────────────────────
        modelBuilder.Entity<MemoryEntity>(entity =>
        {
            entity.Property(e => e.Id).HasConversion(guidToTextConverter);
            entity.Property(e => e.Type).HasConversion<int>(); // INTEGER not text
            entity.Property(e => e.Embedding).HasConversion(floatArrayToBlobConverter);
            entity.Property(e => e.OccurredAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.Property(e => e.CreatedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.Property(e => e.ResolvedAt).HasConversion(nullableDateTimeOffsetToStringConverter);
            entity.Property(e => e.AnchoredAt).HasConversion(nullableDateTimeOffsetToStringConverter);
            entity.Property(e => e.Tier).HasConversion<string>();           // DecayTier as TEXT
            entity.Property(e => e.Provenance).HasConversion<string>();     // EpistemicTier as TEXT
            entity.HasIndex(e => e.Type).HasDatabaseName("ix_memories_type");
            entity.HasIndex(e => e.OccurredAt).HasDatabaseName("ix_memories_occurred").IsDescending();
            // Issue #62 (2026-05-23) — walk-back substrate-correction.
            entity.HasIndex(e => e.Validity).HasDatabaseName("ix_memories_validity");
        });

        // ── MemoryLinkEntity (composite PK + 2 FKs to memories) ────────
        modelBuilder.Entity<MemoryLinkEntity>(entity =>
        {
            entity.HasKey(e => new { e.SourceId, e.TargetId, e.Relationship });
            entity.Property(e => e.SourceId).HasConversion(guidToTextConverter);
            entity.Property(e => e.TargetId).HasConversion(guidToTextConverter);
            entity.Property(e => e.CreatedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => e.SourceId).HasDatabaseName("ix_memory_links_source");
            entity.HasIndex(e => e.TargetId).HasDatabaseName("ix_memory_links_target");

            // FKs to MemoryEntity. EF Core will generate the FK constraints.
            entity.HasOne<MemoryEntity>()
                .WithMany()
                .HasForeignKey(e => e.SourceId)
                .OnDelete(DeleteBehavior.NoAction);
            entity.HasOne<MemoryEntity>()
                .WithMany()
                .HasForeignKey(e => e.TargetId)
                .OnDelete(DeleteBehavior.NoAction);
        });

        // ── MemoryContradictionEntity (composite PK) ───────────────────
        modelBuilder.Entity<MemoryContradictionEntity>(entity =>
        {
            entity.HasKey(e => new { e.NewMemoryId, e.ExistingMemoryId });
            entity.Property(e => e.NewMemoryId).HasConversion(guidToTextConverter);
            entity.Property(e => e.ExistingMemoryId).HasConversion(guidToTextConverter);
            entity.Property(e => e.FlaggedAt).HasConversion(dateTimeOffsetToStringConverter);
        });

        // ── MemoryAuditEntity ──────────────────────────────────────────
        modelBuilder.Entity<MemoryAuditEntity>(entity =>
        {
            entity.Property(e => e.MemoryId).HasConversion(guidToTextConverter);
            entity.Property(e => e.OccurredAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => e.MemoryId).HasDatabaseName("ix_audit_memory");
            entity.HasIndex(e => e.OccurredAt).HasDatabaseName("ix_audit_time").IsDescending();
            entity.HasIndex(e => e.Action).HasDatabaseName("ix_audit_action");
        });

        // ── State blob singletons ──────────────────────────────────────
        // EF needs no extra config — INT PK + TEXT JSON column.

        // ── EmotionalStateHistoryEntity ────────────────────────────────
        modelBuilder.Entity<EmotionalStateHistoryEntity>(entity =>
        {
            entity.Property(e => e.RecordedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => e.RecordedAt).HasDatabaseName("ix_emotional_history_time").IsDescending();
        });

        // ── EmotionalContributionEntity ────────────────────────────────
        modelBuilder.Entity<EmotionalContributionEntity>(entity =>
        {
            entity.Property(e => e.Id).HasConversion(guidToTextConverter);
            entity.Property(e => e.Embedding).HasConversion(floatArrayToBlobConverter);
            entity.Property(e => e.CreatedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => e.CreatedAt).HasDatabaseName("ix_contributions_created").IsDescending();
        });

        // ── ConfabulationFlagEntity ────────────────────────────────────
        modelBuilder.Entity<ConfabulationFlagEntity>(entity =>
        {
            entity.Property(e => e.Id).HasConversion(guidToTextConverter);
            entity.Property(e => e.FlaggedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => e.FlaggedAt).HasDatabaseName("ix_confab_flags_time").IsDescending();
        });

        // ── ConversationThreadEntity ───────────────────────────────────
        modelBuilder.Entity<ConversationThreadEntity>(entity =>
        {
            entity.Property(e => e.Id).HasConversion(guidToTextConverter);
            entity.Property(e => e.StartedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.Property(e => e.LastMessageAt).HasConversion(dateTimeOffsetToStringConverter);
        });

        // ── ConversationMessageEntity ──────────────────────────────────
        modelBuilder.Entity<ConversationMessageEntity>(entity =>
        {
            entity.Property(e => e.ThreadId).HasConversion(guidToTextConverter);
            entity.Property(e => e.SentAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.HasIndex(e => new { e.ThreadId, e.SentAt }).HasDatabaseName("ix_conv_messages_thread");

            entity.HasOne<ConversationThreadEntity>()
                .WithMany()
                .HasForeignKey(e => e.ThreadId)
                .OnDelete(DeleteBehavior.NoAction);
        });

        // ── ClosedConversationRecordEntity ─────────────────────────────
        modelBuilder.Entity<ClosedConversationRecordEntity>(entity =>
        {
            entity.Property(e => e.Id).HasConversion(guidToTextConverter);
            entity.Property(e => e.ThreadId).HasConversion(guidToTextConverter);
            entity.Property(e => e.ClosedAt).HasConversion(dateTimeOffsetToStringConverter);
            entity.Property(e => e.Embedding).HasConversion(floatArrayToBlobConverter);
            entity.HasIndex(e => e.ClosedAt).HasDatabaseName("ix_closed_conv_closed_at").IsDescending();
            entity.HasIndex(e => e.ThreadId).HasDatabaseName("ix_closed_conv_thread_id");
        });
    }

    /// <summary>
    /// float[] → byte[] conversion using Buffer.BlockCopy.
    /// Each float = 4 bytes; total = floats.Length × 4.
    /// </summary>
    private static byte[] FloatArrayToBytes(float[] floats)
    {
        var bytes = new byte[floats.Length * sizeof(float)];
        Buffer.BlockCopy(floats, 0, bytes, 0, bytes.Length);
        return bytes;
    }

    private static float[] BytesToFloatArray(byte[] bytes)
    {
        var floats = new float[bytes.Length / sizeof(float)];
        Buffer.BlockCopy(bytes, 0, floats, 0, bytes.Length);
        return floats;
    }
}
