<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <RootNamespace>AniRuntime.Friend</RootNamespace>
    <AssemblyName>AniRuntime.Friend</AssemblyName>
  </PropertyGroup>

</Project>
